# An Introduction to Pandas

#### Import the pandas package

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'name':['Bob','Jen','Tim'],
                   'age':[20,30,40],
                   'pet':['cat', 'dog', 'bird']})

df

In [ ]:
print(df.columns)
print(df.index)

In [ ]:
print(df['name'])
print(df.name)

In [ ]:
df[['name','pet']]

In [ ]:
df.iloc[0]

In [ ]:
df.sort_values('pet',inplace=True, ascending=True)

In [ ]:
df

In [ ]:
df.loc[0] #index based

In [ ]:
df.iloc[0] #relative position based indexing

In [ ]:
df.iloc[:,2]

In [ ]:
df.iloc[-1,:]

In [ ]:
sales = [100,130,119,92,35]
customer_account = ['B100','J101','X102','P103','R104']
city = ['BOS','LA','NYC','SF','CHI']

#### Create a DataFrame with the data above

In [ ]:
import numpy as np
import pandas as pd
import psycopg2 as ps

In [ ]:
data.survived[(data.sex=='male')&(data.age>=18)].mean()

#### What was the survival rate for women and children?

The mean method is the same as AVERAGE in SQL.

In [ ]:
data.survived[(data.sex=='female')|(data.age<18)].mean()

#### Use groupby to compare the survival rates of men and women

The `groupby` method is one of the most important tools you will use in your day to day work.

It's main input parameter is either a string denoting a column name or a list of strings denoting a list of column names.

It's output is a GroupBy object which is very similar to a dataframe.

The operation of groupby is the same as SQL GROUPBY.

For more info see the [docs](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.groupby.html).

In [ ]:
data.groupby('sex')['survived'].mean()

#### Create a DataFrame with groupby

In [ ]:
new = data.groupby(['sex','pclass'])['survived','age'].mean()
new

## Importing and Exporting Data with Pandas

#### Pandas has easy to use functions for importing and exporting different data types: 
- CSV Files 
- Excel Worksheets
- Queries from Databases

Strata Scratch notebooks will exclusively be import data from our platform so we will not be covering other import techniques.

## More Basic Pandas Exercises

#### What was the average age of the survivors?

#### What was the combined survival rate of both children (age less than 18) and seniors (age greater than 60)?

#### Group by pClass and investigate average survival rate, age and fare

#### Create a CSV with the names and ages of the surivors and another CSV file with the names and ages of the deceased. Please refer to documention (to_csv method) to complete the exercise.

[Documentation for the method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html)